### ISSUE TITLE
Error with bundled brython.js

### ISSUE THREAD

**Issue by 1951FDG** [denis-migdal/Brython-AOT#2]
```
error: Uncaught (in promise) ReferenceError: scope is not defined
	let js_ast = __BRYTHON__.py2js(pycode, "exec");
	                         ^
    at analyze_cells (eval at <anonymous> (file:///Users/Developer/Brython-AOT/Brython-AOT.ts:81:4), <anonymous>:16982:6)
    at analyze_block (eval at <anonymous> (file:///Users/Developer/Brython-AOT/Brython-AOT.ts:81:4), <anonymous>:17044:33)
    at analyze_child_block (eval at <anonymous> (file:///Users/Developer/Brython-AOT/Brython-AOT.ts:81:4), <anonymous>:17054:5)
    at analyze_block (eval at <anonymous> (file:///Users/Developer/Brython-AOT/Brython-AOT.ts:81:4), <anonymous>:17037:6)
    at symtable_analyze (eval at <anonymous> (file:///Users/Developer/Brython-AOT/Brython-AOT.ts:81:4), <anonymous>:17058:8)
    at Object.$B._PySymtable_Build (eval at <anonymous> (file:///Users/Developer/Brython-AOT/Brython-AOT.ts:81:4), <anonymous>:16885:1)
    at Object.$B.py2js (eval at <anonymous> (file:///Users/Developer/Brython-AOT/Brython-AOT.ts:81:4), <anonymous>:4810:17)
    at convertFile (file:///Users/Developer/Brython-AOT/Brython-AOT.ts:37:27)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async file:///Users/Developer/Brython-AOT/Brython-AOT.ts:111:
```

Workaround with this version of brython.js, http://brython.info/src/brython.js, no errors !!

**Comment by denis-migdal** [comment]
Currently, we use an old version of the `brython.js`. I'll try to upgrade it and verify if it works.

**Comment by denis-migdal** [comment]
Update done in commit 2b30f43

The submodule enables to see which version of Brython we are using and to facilitate update / versions troubleshooting.


Does the new version of Brython works for your code ?
If not, can you provide me with an example to reproduce your error ?
If it works, can you close this issue ?

Thanks.
